### ISSUE TITLE
Question - SkypeForBusiness Bot deployment in Azure

### ISSUE THREAD

**Issue by virendrak** [ankitbko/SkypeForBusinessBot#4]
Hi @ankitbko, First things first, sorry for asking so many questions.

I have few more doubts, need your expert advice on the same.

_FYI: My current Bot, which is developed using Bot Framework & C#, works fine for Skype, MS Team and Web-Chat channel._
- As per prerequisite to use the Skype-For-Business Channel,  this application should be in running state to run/response. Will it work if I'll deploy in Azure (as we generally deploy a Bot as App Service), after using your code (required function to run Skype-For-Business) in my existing bot 
- What should I use for saving (like you used [memory or redis](https://github.com/ankitbko/SkypeForBusinessBot/issues/2#issuecomment-271943891)) if I host in Azure as App Service.
- Any other precaution or limitation or suggestion for this SkypeForBusiness channel approach, which I have to keep in mind.

Thanks in Advance!

Regards,
Viren

**Comment by ankitbko** [comment]
Hey Virendra,
No need to apologize, it is great that you are coming up with these questions. I'll answer all three of your questions - 
In your typical scenarios, the bot is hosted as a separate service whose endpoint is then registered at Bot Portal. This is necessary because the chat messages from a *channel* such as FB first goes to Bot Connector which then adapts and routes it to our bot. However for this application to run, Skype For Business/Lync client should be running. I then intercept the messages sent to the user which has signed in to the Skype For Business/Lync using Lync 2013 SDK. But since now I already have the message, I no longer have to rely on Bot Connector. Therefore I bootstrap and start my bot locally within the running application itself. In this case I do not even have to host the bot as separate web application. The complete setup runs locally on the system where Skype For Business/Lync is running.

Now since I do not send messages to Bot Connector, the Bot Storage Servicedoes not have conversation id's with it. So I cannot, in general, use it to store my context and conversation data. Therefore I have to manage it locally. It turns out it is simple to switch from Bot Storage Service to our local database. I have written a [RedisStore](https://github.com/ankitbko/Microsoft.Bot.Builder.RedisStore) which I initially used in this project. However since everyone does not have Redis available so I switched to InMemory storage. For any production use you should **not** use InMemory storage service. Either you can use my Redis implementation or write your own provider for any database.

If you actually want to use Skype For Business as a channel in production, I had not recommend using Lync SDK. Alternatively there are set of APIs called  [Unified Communications Web API](https://msdn.microsoft.com/en-us/skype/ucwa/unifiedcommunicationswebapi2_0) which provides a better way to receive and send messages using Skype for Business. I have used that too earlier and can confirm that it works and integrates with Bot Framework.

Let me know if this helps and please feel free to ask any questions you may have.

**Comment by virendrak** [comment]
@ankitbko, Thank you so much for detailed information. Really Appreciate!!!!!
